/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.alexxicatto.gerenciamentovendaimoveis;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.text.NumberFormat;

/**
 *
 * @author alexxicatto
 */
public class Formulario extends javax.swing.JFrame {

    private String radioButtonSelected;
    List<Imovel> imoveis = new ArrayList<>();

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        nomeCompletoLabel = new javax.swing.JLabel();
        nomeCompletoTextField = new javax.swing.JTextField();
        descricaoLabel = new javax.swing.JLabel();
        descricaoScrollPane = new javax.swing.JScrollPane();
        descricaoTextArea = new javax.swing.JTextArea();
        categoriaLabel = new javax.swing.JLabel();
        residencialRadioButton = new javax.swing.JRadioButton();
        comercialRadioButton = new javax.swing.JRadioButton();
        tipoLabel = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        valorVendaLabel = new javax.swing.JLabel();
        valorVendaTextField = new javax.swing.JTextField();
        cadastrarButton = new javax.swing.JButton();
        visualizarButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        limparTelaMenuItem = new javax.swing.JMenuItem();
        excluirCadastroMenuItem = new javax.swing.JMenuItem();
        excluirTodosCadastrosMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Vendas");
        setResizable(false);

        nomeCompletoLabel.setText("Nome Completo:");

        nomeCompletoTextField.setToolTipText("Digite o nome completo.");

        descricaoLabel.setText("Descrição:");

        descricaoTextArea.setColumns(20);
        descricaoTextArea.setLineWrap(true);
        descricaoTextArea.setRows(5);
        descricaoScrollPane.setViewportView(descricaoTextArea);

        categoriaLabel.setText("Categoria:");
        categoriaLabel.setName(""); // NOI18N

        buttonGroup.add(residencialRadioButton);
        residencialRadioButton.setText("Residencial");
        residencialRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residencialRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(comercialRadioButton);
        comercialRadioButton.setText("Comercial");
        comercialRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comercialRadioButtonActionPerformed(evt);
            }
        });

        tipoLabel.setText("Tipo:");

        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa", "Chácara", "Sala", "Salão", "Sítio" }));

        valorVendaLabel.setText("Valor de Venda:");

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        visualizarButton.setText("Visualizar");
        visualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarButtonActionPerformed(evt);
            }
        });

        Menu.setText("Editar");

        limparTelaMenuItem.setText("Limpar Tela");
        limparTelaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTelaMenuItemActionPerformed(evt);
            }
        });
        Menu.add(limparTelaMenuItem);

        excluirCadastroMenuItem.setText("Excluir Um Cadastro");
        excluirCadastroMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCadastroMenuItemActionPerformed(evt);
            }
        });
        Menu.add(excluirCadastroMenuItem);

        excluirTodosCadastrosMenuItem.setText("Excluir Todos Os Cadastros");
        excluirTodosCadastrosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirTodosCadastrosMenuItemActionPerformed(evt);
            }
        });
        Menu.add(excluirTodosCadastrosMenuItem);

        MenuBar.add(Menu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeCompletoLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(descricaoLabel)
                        .addComponent(descricaoScrollPane)
                        .addComponent(nomeCompletoTextField))
                    .addComponent(categoriaLabel)
                    .addComponent(comercialRadioButton)
                    .addComponent(residencialRadioButton))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valorVendaLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(visualizarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastrarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valorVendaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tipoLabel)
                                .addGap(0, 213, Short.MAX_VALUE))
                            .addComponent(tipoComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompletoLabel)
                    .addComponent(tipoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoLabel)
                    .addComponent(valorVendaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricaoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorVendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoriaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(residencialRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comercialRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(visualizarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarButton)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:

        String[] checkStrings = new String[5];

        checkStrings[0] = nomeCompletoTextField.getText();
        checkStrings[1] = descricaoTextArea.getText();
        checkStrings[2] = radioButtonSelected;
        checkStrings[3] = tipoComboBox.getSelectedItem().toString();
        checkStrings[4] = valorVendaTextField.getText();

        if (!hasNullFields(checkStrings)) {

            try {

                double valorVenda = Double.parseDouble(checkStrings[4]);
                String valorVendaFormatted = NumberFormat.getCurrencyInstance().format(valorVenda);

                checkStrings[4] = valorVendaFormatted;

                Imovel imovel = new Imovel(
                        checkStrings[0],
                        checkStrings[1],
                        checkStrings[2],
                        checkStrings[3],
                        checkStrings[4]);

                imoveis.add(imovel);

                JOptionPane.showMessageDialog(rootPane, "Cadastro efetuado com sucesso");
                resetAllFields();
            } catch (NumberFormatException e) {

                JOptionPane.showMessageDialog(rootPane, "Valor da venda inválido: utilize somente números");
            }

        } else {

            JOptionPane.showMessageDialog(rootPane, "Todos os campos devem ser preenchidos");
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void residencialRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residencialRadioButtonActionPerformed
        // TODO add your handling code here:
        radioButtonSelected = residencialRadioButton.getText();
    }//GEN-LAST:event_residencialRadioButtonActionPerformed

    private void comercialRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comercialRadioButtonActionPerformed
        // TODO add your handling code here:
        radioButtonSelected = comercialRadioButton.getText();
    }//GEN-LAST:event_comercialRadioButtonActionPerformed

    private void visualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarButtonActionPerformed
        // TODO add your handling code here:
        new Informacoes(imoveis, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_visualizarButtonActionPerformed

    private void limparTelaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTelaMenuItemActionPerformed
        // TODO add your handling code here:
        resetAllFields();
    }//GEN-LAST:event_limparTelaMenuItemActionPerformed

    private void excluirCadastroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCadastroMenuItemActionPerformed
        // TODO add your handling code here:

        String numeroCadastroString = JOptionPane.showInputDialog(rootPane, "Informe o número do cadastro (posição do cadastro na lista):");

        if (numeroCadastroString.matches("^[0-9][1-9]*$")) {
            int numeroCadastro = Integer.parseInt(numeroCadastroString);

            if (numeroCadastro < imoveis.size()) {
                imoveis.remove(numeroCadastro);
                JOptionPane.showMessageDialog(rootPane, "O Cadastro informado foi deletado com sucesso");
            } else {
                JOptionPane.showMessageDialog(rootPane, "O Cadastro informado não existe");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Utilize somente números");
        }
    }//GEN-LAST:event_excluirCadastroMenuItemActionPerformed

    private void excluirTodosCadastrosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirTodosCadastrosMenuItemActionPerformed
        // TODO add your handling code here:
        if (!imoveis.isEmpty()) {
            imoveis.clear();
            JOptionPane.showMessageDialog(rootPane, "Todos os cadastros foram deletados com sucesso");
        } else {
            
            JOptionPane.showMessageDialog(rootPane, "Não há nenhum cadastro existente para ser deletado");
        }
    }//GEN-LAST:event_excluirTodosCadastrosMenuItemActionPerformed

    private void resetAllFields() {
        nomeCompletoTextField.setText("");
        descricaoTextArea.setText("");
        buttonGroup.clearSelection();
        tipoComboBox.setSelectedIndex(0);
        valorVendaTextField.setText("");
    }

    private boolean hasNullFields(String[] fields) {

        for (int i = 0; i < fields.length; i++) {

            if (fields[i].isEmpty()) {
                return true;
            }
        }

        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JRadioButton comercialRadioButton;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JScrollPane descricaoScrollPane;
    private javax.swing.JTextArea descricaoTextArea;
    private javax.swing.JMenuItem excluirCadastroMenuItem;
    private javax.swing.JMenuItem excluirTodosCadastrosMenuItem;
    private javax.swing.JMenuItem limparTelaMenuItem;
    private javax.swing.JLabel nomeCompletoLabel;
    private javax.swing.JTextField nomeCompletoTextField;
    private javax.swing.JRadioButton residencialRadioButton;
    private javax.swing.JComboBox<String> tipoComboBox;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JLabel valorVendaLabel;
    private javax.swing.JTextField valorVendaTextField;
    private javax.swing.JButton visualizarButton;
    // End of variables declaration//GEN-END:variables
}
