/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.alexxicatto.gerenciamentovendaimoveis;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author alexxicatto
 */
public class Informacoes extends javax.swing.JFrame {

    List<Imovel> imoveis;
    Formulario formulario;
    
    public Informacoes() {
        initComponents();
    }

    public Informacoes(List<Imovel> imoveis, Formulario formulario) {
        initComponents();
        
        this.imoveis = imoveis;
        this.formulario = formulario;
        
        int imoveisSize = imoveis.size();
        
        for (Imovel imovel : imoveis) {
            
            StringBuilder sb = new StringBuilder();
            JTextArea textArea = new JTextArea(5, 20);
            textArea.setEditable(false);
            textArea.setFocusable(false);
            textArea.setLineWrap(true);
            
            sb.append("Nome Completo: ");
            sb.append(imovel.getNomeCompleto());
            sb.append("\nDescrição: ");
            sb.append(imovel.getDescricao());
            sb.append("\nCategoria: ");
            sb.append(imovel.getCategoria());
            sb.append("\nTipo: ");
            sb.append(imovel.getTipo());
            sb.append("\nValor de venda: ");
            sb.append(imovel.getValorVenda());
            
            textArea.setText(sb.toString());
            informacaoPanel.add(textArea);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        informacaoPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        voltarMenu = new javax.swing.JMenu();
        sobreMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 308));
        setResizable(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        informacaoPanel.setLayout(new javax.swing.BoxLayout(informacaoPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane2.setViewportView(informacaoPanel);

        voltarMenu.setIcon(new javax.swing.ImageIcon("/Users/alexxicatto/Downloads/arrow_back-black-18dp/1x/baseline_arrow_back_black_18dp.png")); // NOI18N
        voltarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(voltarMenu);

        sobreMenu.setText("Sobre");
        sobreMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sobreMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(sobreMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMenuMouseClicked
        // TODO add your handling code here:
        formulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_voltarMenuMouseClicked

    private void sobreMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreMenuMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Nome: Alex Di Vennet Xicatto\nCódigo: 815049");
    }//GEN-LAST:event_sobreMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel informacaoPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu sobreMenu;
    private javax.swing.JMenu voltarMenu;
    // End of variables declaration//GEN-END:variables
}
